[package]
name = "inputsync-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
toml = { workspace = true }
directories = { workspace = true }
tracing = { workspace = true }
bitflags = { version = "2", features = ["serde"] }
